##### This is nsweeting2's Hxyprland config file.
##### Refer to the wiki for more information.
##### https://wiki.hyprland.org/Configuring/Configuring-Hyprland/
##### DSM Settings handles some of this now, #DSM to note this

##### DSM CURSOR #####
source = ./dms/cursor.conf

##### DSM COLORS #####
source = ./dms/colors.conf

##### DSM Outputs #####
source = ./dms/outputs.conf

##### DSM BINDS #####
source = ./dms/binds.conf

##### DSM WINDOW RULES #####
source = ./dms/windowrules.conf

##### DSM LAYOUT #####
source = ./dms/layout.conf

##### INPUT #####
input {
    kb_layout = us
    numlock_by_default = true
    follow_mouse = 2
    sensitivity = 0
}

##### CURSOR #####
cursor {
    no_hardware_cursors = true
}

##### MISC #####
misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
    vrr = 1
}

##### ECOSYSTEM #####
ecosystem {
    no_update_news = true
    no_donation_nag = true
}

###### LAYOUT #####
general {
    layout = dwindle
}

dwindle {
    pseudotile = true
    preserve_split = true
    smart_resizing = true
}

##### EXEC ONCE #####
# XDG Desktop Portal
exec-once = systemctl --user start xdg-desktop-portal-hyprland
exec-once = sleep 1 && systemctl --user restart xdg-desktop-portal
# Keyring
exec-once = gnome-keyring-daemon --start --components=secrets
# HyprBars
exec-once = bash -c 'if [ ! -f ~/.config/hypr/.hyprpm-initialized ]; then hyprpm add https://github.com/hyprwm/hyprland-plugins && hyprpm enable hyprbars && touch ~/.config/hypr/.hyprpm-initialized; fi && hyprpm update && hyprpm reload -n'

##### ENVIROMENT #####
env = QT_QPA_PLATFORM,wayland # Make QT Apps use Wayland
env = ELECTRON_OZONE_PLATFORM_HINT,auto # Make Electron use Wayland
env = QT_QPA_PLATFORMTHEME,qt5ct # Make QT match GTK3 Colors
env = QT_QPA_PLATFORMTHEME_QT6,qt5ct # Make QT match GTK3 Colors
env = FREERDP_ASKPASS,/usr/libexec/openssh/gnome-ssh-askpass

##### PLUGINS #####

# HyprBars
plugin {
    hyprbars {
        # --- Structural Settings ---
        bar_height = 28
        bar_color = rgb(242424)
        col.text = $primary                 # Electric Orange for the title
        bar_text_font = Noto Sans Bold
        bar_text_size = 10
        bar_text_align = center

        # --- The "Modern" Border Look ---
        # Setting precedence to false lets the window border wrap the bar
        bar_precedence_over_border = true

        # --- Buttons: Using your $error and $outline ---
        # Close Button (Error Red)
        hyprbars-button = $primary, 14, X, hyprctl dispatch killactive

        # Float/Minimize Button (Outline Blue)
        # hyprbars-button = $outline, 12, F, hyprctl dispatch togglefloating

        # Padding & Spacing
        bar_button_padding = 8
        bar_padding = 10
    }
}
