##### Youtube Music PWA #####
# 1. Open on workspace 1 at startup
windowrule = match:initial_title ^(music.youtube.com\_\/)$, workspace 1
# 2. Make sure we are tiled and not floating
windowrule = match:initial_title ^(music.youtube.com\_\/)$, tile on

##### Outlook WebApp PWA #####
# 1. Open on workspace 1 at startup
windowrule = match:initial_title ^(outlook.office.com\_/mail\/)$, workspace 1
# 2. Make sure we are tiled and not floating
windowrule = match:initial_title ^(outlook.office.com\_\/mail\/)$, tile on

##### Spiceworks PWA #####
# 1. Open on workspace 2 at startup
windowrule = match:initial_title ^(cayugacc.on.spiceworks.com\_\/)$, workspace 2
# 2. Make sure we are tiled and not floating
windowrule = match:initial_title ^(music.youtube.com\_\/)$, tile on

##### Remote Desktop Manager #####
# 1. Open on workspace 9 at startup
windowrule = match:initial_title ^(Remote Desktop Manager)$, workspace 9
# 2. Make sure we are tiled and not floating
windowrule = match:initial_title ^(Remote Desktop Manager)$, tile on
# 3. Maximize the window on startup
windowrule = match:initial_title ^(Remote Desktop Manager)$, maximize on

##### RDP for F140-03 #####
# 1. Open on Workspace 10 at startup
windowrule = match:initial_title ^(F140A-03-RDP)$, workspace 10
# 2. Make sure we are tiled and not floating
windowrule = match:class ^(F140A-03-RDP)$, tile on
# 3. Maximize the window on startup
windowrule = match:initial_title ^(F140A-03-RDP)$, maximize on

##### Floaters - Anything that should float  #####
# 1. Calculator
windowrule = match:class ^(org.gnome.Calculator)$, float on
# 2. Camera
windowrule = match:class ^(org.gnome.Snapshot)$, float on

